### ISSUE TITLE
I can't connect my appstore account

### ISSUE THREAD

**Issue by gokhanamal** [socketkit/bugs#8] opened 2021-04-07 06:28 UTC
I generated an access token but when I click the create a button on the AppStore integration page "https://core.socketkit.com/v1/integrations/appstore-connect" endpoint returns HTTP code 500.

<img width="649" alt="Screen Shot 2021-04-07 at 09 27 05" src="https://user-images.githubusercontent.com/21364542/113820580-90c0da80-9783-11eb-8e51-a1083178c014.png">
<img width="393" alt="Screen Shot 2021-04-07 at 09 26 51" src="https://user-images.githubusercontent.com/21364542/113820586-91f20780-9783-11eb-95bf-fd74fb03e28d.png">

**Comment by anonrig** [comment] 2021-04-07 07:50
Hi @gokhanamal 

Thank you for your feedback. Upon investigation we realized that the token provided by AppStore Connect was not valid for your case, since we are validating the token upon their sales endpoint (whether it is a valid sales token, and you're eligible/have necessary sales on your AppStore Connect account).

This was a false positive and we've updated our error message according to this. The new error message for this unhandled case is: `Token validation failed. Please, make sure you've entered a correct token and have valid sales on your AppStore account.`

I'm closing this issue. If there is a regression on this issue, please reply on this thread.

Thanks!

**Closed by anonrig** 2021-04-07 07:50 UTC
